# v5 - cache body data in localStorage, add 5 new conditions to frontend
services:
  - type: web
    name: cafeteria-recommender
    runtime: python
    plan: free
    buildCommand: pip install -r chimei/requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT chimei.deploy_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
